services:
  nur-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:80
    volumes:
      - .:/app
    container_name: nur-app
    restart: always
    depends_on:
      - nur-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: nur-db
      DB_PORT: 3307
      DB_DATABASE: nutrinur2
      DB_USERNAME: pablo
      DB_PASSWORD: Lm12345
    networks:
      - nur-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      retries: 3
      start_period: 30s
    command: ["/bin/sh", "-c", "php migrate.php && apache2-foreground"]
    #Primero ejecuta php migrate.php para crear las tablas. Luego arranca Apache con apache2-foreground para que el contenedor siga ejecutándose

  nur-db:
    image: mysql:8.0
    container_name: nur-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lm12345
      MYSQL_DATABASE: nutrinur2
      MYSQL_USER: pablo
      MYSQL_PASSWORD: Lm12345
    ports:
      - 3307:3306
    networks:
      - nur-network
    volumes:
      - mysql_data:/var/lib/mysql

  nur-consumidor:
    build:
      context: src/Infraestructura/Consumidor
      dockerfile: Dockerfile
    container_name: nur-consumidor
    volumes:
      - .:/app
    working_dir: /app/src/Infraestructura/Consumidor
    networks:
      - nur-network
    depends_on:
      - nur-app
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(0);'"]
      interval: 10s
      retries: 3
      start_period: 5s

networks:
  nur-network:
    driver: bridge

volumes:
  mysql_data:
