services:
  sqlserver:
    image: dagner29/mysqlserver:latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: Password2025
      ACCEPT_EULA: "Y"
    networks:
      - delivery-network
    ports:
      - "1434:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    image: dagner29/deliveryapi:1.0.0    
    container_name: delivery-api
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DeliveryDB;User=sa;Password=Password2025;TrustServerCertificate=True;"
    ports:
      - "8085:8080"
    networks:
      - delivery-network
     # Aquí 'myapp.dll' es el nombre del archivo de salida de tu aplicación, asegúrate de cambiarlo según corresponda.
  
volumes:
  sqlserver_data:

networks:
  delivery-network:
    driver: bridge  
